"""init: create 7 core tables

Revision ID: dbc59de56c9b
Revises: 'fd1d890a1f0b'
Create Date: 2026-08-06 22:07:06.788173+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc59de56c9b'
down_revision: Union[str, None] = 'fd1d890a1f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
