import React, { useState, useEffect } from 'react';
import { 
  AlertTriangle, 
  Send, 
  Loader2, 
  ArrowLeft, 
  History,
} from 'lucide-react';
import { fetchClarification, submitClarification } from '../api/client';

export default function ClarificationLoop({ requestId, onClarificationComplete, onBack }) {
  const [data, setData] = useState(null);
  const [answersMap, setAnswersMap] = useState({});
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadQuestions() {
      try {
        setLoading(true);
        const res = await fetchClarification(requestId);
        setData(res);

        // Normalize questions array from backend response (res.questions or res.clarification_questions)
        const qList = res.questions || res.clarification_questions || [];
        const initialAnswers = {};
        qList.forEach((_, idx) => {
          initialAnswers[idx] = '';
        });
        setAnswersMap(initialAnswers);
      } catch (err) {
        setError(err.message || 'Failed to load clarification questions.');
      } finally {
        setLoading(false);
      }
    }

    if (requestId) {
      loadQuestions();
    }
  }, [requestId]);

  const handleAnswerChange = (idx, text) => {
    setAnswersMap((prev) => ({
      ...prev,
      [idx]: text,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    const questionsList = data?.questions || data?.clarification_questions || [];
    
    // Build flat array of answer strings expected by ClarificationAnswerInput schema { answers: string[] }
    const answersArray = questionsList.map((q, idx) => {
      const text = answersMap[idx]?.trim();
      return text || 'No additional details provided.';
    });

    const hasEmpty = answersArray.some((ans) => !ans || ans === 'No additional details provided.');
    if (hasEmpty) {
      setError('Please provide responses to all clarification questions to ensure accurate graph re-evaluation.');
      return;
    }

    try {
      setSubmitting(true);
      // submitClarification expects (requestId, answersArray) where answersArray is string[]
      const updatedResult = await submitClarification(requestId, answersArray);
      onClarificationComplete(updatedResult);
    } catch (err) {
      setError(err.message || 'Failed to submit clarification answers.');
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="glass-panel" style={{ padding: '48px', textAlign: 'center' }}>
        <Loader2 size={36} color="#3B82F6" className="animate-spin" style={{ margin: '0 auto 16px' }} />
        <div style={{ fontSize: '1rem', fontWeight: 600, color: '#E2E8F0' }}>
          Fetching Clarification Questions for Request <code style={{ color: '#60A5FA' }}>{requestId}</code>...
        </div>
      </div>
    );
  }

  if (error && !data) {
    return (
      <div className="glass-panel" style={{ padding: '32px' }}>
        <div style={{ color: '#F87171', marginBottom: '16px', fontWeight: 600 }}>
          Error: {error}
        </div>
        <button className="btn-secondary" onClick={onBack}>
          <ArrowLeft size={16} /> Back to Result Summary
        </button>
      </div>
    );
  }

  const questionsList = data?.questions || data?.clarification_questions || [];
  const previousAnswers = data?.answers || data?.clarification_answers || [];
  const round = data?.clarification_round || 1;

  return (
    <div className="glass-panel" style={{ padding: '32px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px', marginBottom: '28px' }}>
        <div>
          <button className="btn-secondary" onClick={onBack} style={{ padding: '4px 12px', fontSize: '0.8rem', marginBottom: '12px' }}>
            <ArrowLeft size={14} /> Back to Summary
          </button>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span className="badge badge-clarification" style={{ fontSize: '0.8rem', padding: '4px 12px' }}>
              <AlertTriangle size={14} /> Clarification Loop — Round #{round}
            </span>
          </div>
          <h2 style={{ fontSize: '1.4rem', fontWeight: 800, marginTop: '8px', color: '#F8FAFC' }}>
            Requirement Clarification Needed
          </h2>
          <p style={{ fontSize: '0.88rem', color: '#94A3B8', marginTop: '4px' }}>
            To improve feasibility score accuracy, please answer the questions below generated by the AI evaluation agent.
          </p>
        </div>
      </div>

      {error && (
        <div style={{ background: 'rgba(239, 68, 68, 0.15)', border: '1px solid rgba(239, 68, 68, 0.4)', color: '#F87171', padding: '12px 16px', borderRadius: '10px', fontSize: '0.88rem', marginBottom: '24px' }}>
          {error}
        </div>
      )}

      {/* Previous Round Answers (if any) */}
      {previousAnswers.length > 0 && (
        <div style={{ background: 'rgba(15, 23, 42, 0.5)', padding: '20px', borderRadius: '14px', border: '1px solid var(--border-glass)', marginBottom: '28px' }}>
          <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#94A3B8', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <History size={16} color="#3B82F6" /> Previous Recorded Clarification Responses
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {previousAnswers.map((ans, idx) => (
              <div key={idx} style={{ background: 'rgba(30, 41, 59, 0.4)', padding: '10px 14px', borderRadius: '8px', fontSize: '0.85rem', color: '#CBD5E1' }}>
                <strong>Response #{idx + 1}:</strong> {ans}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Questions Form */}
      <form onSubmit={handleSubmit}>
        {questionsList.length === 0 ? (
          <div style={{ padding: '24px', textAlign: 'center', color: '#94A3B8' }}>
            No additional questions required. Your project status is set to evaluated.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', marginBottom: '28px' }}>
            {questionsList.map((qText, idx) => (
              <div 
                key={idx} 
                style={{
                  background: 'rgba(15, 23, 42, 0.6)',
                  padding: '20px',
                  borderRadius: '14px',
                  border: '1px solid rgba(245, 158, 11, 0.25)',
                }}
              >
                <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', fontSize: '0.92rem', fontWeight: 700, color: '#F8FAFC', marginBottom: '12px' }}>
                  <span style={{ background: '#F59E0B22', color: '#FBBF24', borderRadius: '6px', padding: '2px 8px', fontSize: '0.8rem', fontWeight: 800 }}>
                    Q{idx + 1}
                  </span>
                  <span>{qText}</span>
                </label>

                <textarea
                  className="glass-input"
                  rows={3}
                  placeholder="Provide specific details, data formats, or operational constraints for this question..."
                  value={answersMap[idx] || ''}
                  onChange={(e) => handleAnswerChange(idx, e.target.value)}
                  required
                />
              </div>
            ))}
          </div>
        )}

        {/* Submit Button */}
        {questionsList.length > 0 && (
          <button
            type="submit"
            className="btn-primary"
            disabled={submitting}
            style={{ width: '100%', justifyContent: 'center', padding: '14px', fontSize: '1rem', background: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)' }}
          >
            {submitting ? (
              <>
                <Loader2 size={20} className="animate-spin" /> Submitting Responses & Re-evaluating LangGraph Pipeline...
              </>
            ) : (
              <>
                <Send size={18} /> Submit Answers & Re-evaluate Feasibility Score
              </>
            )}
          </button>
        )}
      </form>
    </div>
  );
}
