"""
tests/test_migrations.py
Integration tests for the Alembic migration chain.

Why these live apart from the rest of the suite
-----------------------------------------------
`tests/conftest.py` builds its schema with `Base.metadata.create_all` on an
in-memory SQLite engine. That is the right trade-off for fast unit tests, but
it means the migrations themselves are never exercised: a broken
`down_revision`, a non-reversible `downgrade()`, or a model changed without a
matching revision would all keep the suite green and only fail in production.

These tests therefore run against a real PostgreSQL with the pgvector
extension (revision a3f8c2b10e47 needs it, so SQLite cannot be used), started
on demand via testcontainers. They are marked `integration` and skip cleanly
when Docker is unavailable, keeping the default `pytest` run hermetic.

Run explicitly with:  pytest -m integration
"""

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory

pytestmark = pytest.mark.integration

PROJECT_ROOT_MARKER = "alembic.ini"


def _alembic_config(database_url: str) -> Config:
    """Build an Alembic config pointed at a throwaway database.

    `env.py` reads DATABASE_URL from `backend.config` at import time, so the
    URL is injected here via `set_main_option`, which env.py's own
    `set_main_option` call would otherwise clobber. See the monkeypatch in
    `postgres_url` for how that is neutralised.
    """
    config = Config(PROJECT_ROOT_MARKER)
    config.set_main_option("sqlalchemy.url", database_url)
    return config


@pytest.fixture(scope="module")
def postgres_url(monkeypatch_module):
    """Start a disposable pgvector-enabled PostgreSQL and yield its async URL."""
    testcontainers = pytest.importorskip(
        "testcontainers.postgres",
        reason="testcontainers not installed; run `uv sync --extra dev`",
    )
    try:
        container = testcontainers.PostgresContainer("pgvector/pgvector:pg16")
        container.start()
    except Exception as exc:  # Docker daemon absent or unreachable
        pytest.skip(f"Docker unavailable for integration tests: {exc}")

    url = container.get_connection_url().replace(
        "postgresql+psycopg2://", "postgresql+asyncpg://", 1
    )
    # env.py overrides sqlalchemy.url from backend.config at import time.
    # Point that module-level constant at the container instead.
    monkeypatch_module.setenv("DATABASE_URL", url)
    import backend.config

    monkeypatch_module.setattr(backend.config, "DATABASE_URL", url, raising=False)
    try:
        yield url
    finally:
        container.stop()


def test_revision_chain_has_single_head():
    """A second head means two migrations branched off the same parent.

    Alembic refuses `upgrade head` in that state, so this catches the
    merge-conflict-in-migrations case without needing a database at all.
    """
    script = ScriptDirectory.from_config(Config(PROJECT_ROOT_MARKER))
    heads = script.get_heads()
    assert len(heads) == 1, f"expected exactly one head, found {heads}"


def test_every_down_revision_resolves():
    """Guards against a `down_revision` pointing at a non-existent id."""
    script = ScriptDirectory.from_config(Config(PROJECT_ROOT_MARKER))
    known = {rev.revision for rev in script.walk_revisions()}
    for rev in script.walk_revisions():
        if rev.down_revision is None:
            continue
        parents = (
            rev.down_revision
            if isinstance(rev.down_revision, (list, tuple))
            else [rev.down_revision]
        )
        for parent in parents:
            assert parent in known, (
                f"revision {rev.revision} points at unknown parent {parent}"
            )


def test_upgrade_head_applies_cleanly(postgres_url):
    """The full chain applies from an empty database."""
    from alembic import command

    command.upgrade(_alembic_config(postgres_url), "head")


def test_downgrade_then_upgrade_is_reversible(postgres_url):
    """Every `downgrade()` undoes its `upgrade()` well enough to re-apply.

    This is what makes a production rollback survivable; a downgrade that
    silently leaves a column behind fails on the second upgrade.
    """
    from alembic import command

    config = _alembic_config(postgres_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")


def test_models_match_migrations(postgres_url):
    """Fails when a model was edited without generating a revision.

    `alembic check` autogenerates against the live schema and raises if any
    diff remains — the drift that otherwise surfaces as a runtime
    UndefinedColumnError on the first INSERT.
    """
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    config = _alembic_config(postgres_url)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"models drifted from migrations: {exc}")
