"""
models/db_schemes/requirementshub/schemes/fact_extraction.py
ORM model for the `fact_extractions` table.
Stores structured facts extracted by the LLM pipeline from a raw submission.
1:1 relationship with submissions (UNIQUE constraint on submission_id).
"""

import uuid
from sqlalchemy import String, Boolean, Text, ForeignKey, UniqueConstraint, JSON
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
from .base import Base

JSON_TYPE = JSONB().with_variant(JSON, "sqlite")


class FactExtraction(Base):
    __tablename__ = "fact_extractions"
    __table_args__ = (UniqueConstraint("submission_id", name="uq_fact_extraction_submission"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    submission_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("submissions.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Boolean flags from LLM extraction
    has_clear_problem_statement: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    problem_is_ai_solvable: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    requires_new_research: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # Categorical LLM outputs
    # classification | regression | clustering | nlp | computer_vision |
    # time_series | recommendation | optimization | generative | other | unknown
    problem_category: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # none | partial | full
    data_availability: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # yes | no | unknown
    data_volume_sufficient: Mapped[str | None] = mapped_column(String(20), nullable=True)

    ai_technique_identified: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # low | medium | high
    integration_complexity: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # small (<4 weeks) | medium (4-12 weeks) | large (>12 weeks)
    estimated_effort: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # Executive summary generated by LLM
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # JSONB arrays
    extracted_requirements: Mapped[list] = mapped_column(JSON_TYPE, nullable=False, default=list)
    risks_identified: Mapped[list] = mapped_column(JSON_TYPE, nullable=False, default=list)

    # Relationship back to submission
    submission: Mapped["Submission"] = relationship(back_populates="fact_extraction")

    def __repr__(self) -> str:
        return (
            f"<FactExtraction submission_id={self.submission_id} "
            f"category={self.problem_category!r}>"
        )
