"""
models/ReportModel.py
DB operations for the `reports` table.
Stores final Markdown reports generated by the pipeline.
1:1 relationship with submissions.
"""

import logging
import uuid
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from .BaseDataModel import BaseDataModel, to_uuid
from .db_schemes.requirementshub.schemes.report import Report

logger = logging.getLogger("backend.models.report")


class ReportModel(BaseDataModel):

    def __init__(self, db_client: AsyncSession):
        super().__init__(db_client)

    async def create_or_update(
        self,
        submission_id: str | uuid.UUID,
        report_type: str,
        content: str,
        auto_commit: bool = True,
    ) -> Report:
        """
        Upsert a report for a submission.
        Idempotent: if report is regenerated, updates existing row.
        """
        uid = to_uuid(submission_id)
        if not uid:
            raise ValueError(f"Invalid UUID: {submission_id}")
        existing = await self.get_by_submission_id(uid)

        if existing:
            existing.report_type = report_type
            existing.content = content
            if auto_commit:
                await self.db_client.commit()
                await self.db_client.refresh(existing)
            else:
                await self.db_client.flush()
            logger.info("Report updated for submission %s", submission_id)
            return existing

        report = Report(submission_id=uid, report_type=report_type, content=content)
        return await self.save_and_return(report, auto_commit=auto_commit)

    async def save_report(self, report: Report, auto_commit: bool = True) -> Report:
        """Save a Report ORM instance."""
        if isinstance(report, Report):
            return await self.save_and_return(report, auto_commit=auto_commit)
        return await self.create_or_update(
            report["submission_id"], report["report_type"], report["content"], auto_commit=auto_commit
        )

    async def get_by_submission_id(self, submission_id: str | uuid.UUID) -> Report | None:
        """Fetch report by submission UUID. Returns None if not generated yet."""
        uid = to_uuid(submission_id)
        if not uid:
            return None
        result = await self.db_client.execute(
            select(Report).where(Report.submission_id == uid)
        )
        return result.scalar_one_or_none()
